Sprint 17
maxim-papier/TrackerApp pull request #30
Opened 2023-06-28 17:03 UTC by maxim-papier

Приветствую.

Сделаны задачи по 17 спринту. В том числе полностью сделана сцена "Статистика". Чтобы запустить проект придётся `pod install`, чтобы установить Метрику. Редактирование кол-ва выполненных дней нам разрешили не делать, так как в нашей когорте этой фукнции ещё не было.

Заранее спасибо за ревью.

2023-06-29 20:48 UTC, protos17 requested changes

2023-06-29 20:48 UTC, protos17 commented on TrackerAppScreenshotTest/TrackerAppScreenshotTest.swift
> +            rootViewController: TrackersVC(dependencies: dependencyContainer, analytic: YandexMetricaService())
Для запуска тестов здесь необходимо добавить в инициализаторе параметр: pinSevice

2023-06-29 20:48 UTC, protos17 commented on TrackerAppScreenshotTest/TrackerAppScreenshotTest.swift
> +            rootViewController: TrackersVC(dependencies: dependencyContainer, analytic: YandexMetricaService())
Здесь тоже отсутствует pinSevice

2023-06-29 20:48 UTC, protos17 commented on TrackerApp/CoreData/CategoryStore.swift
> +    //    func getCategory(at indexPath: IndexPath) -> Category? {
Лишний закомментированный код рекомендую удалять

2023-06-29 20:48 UTC, protos17 commented on TrackerApp/CoreData/CategoryStore.swift
> +        for category in categories {
Рекомендую упростить до:

return categories.first(where: { $0.id == id })

2023-06-29 20:48 UTC, protos17 commented on TrackerApp/CoreData/RecordStore.swift
> +            if Calendar.current.isDate(record.date, inSameDayAs: currentDate!) {
Рекомендую не использовать принудительное извлечение опционала

2023-06-29 20:48 UTC, protos17 commented on TrackerApp/Scenes/Cells/ColorCell.swift
>  class ColorCell: UICollectionViewCell {
Рекомендую указать как final

2023-06-29 20:48 UTC, protos17 commented on TrackerApp/Scenes/EditTracker/EditTrackerViewModel.swift
> +        print("Checking validity")
printы не принято пушить в репозиторий

2023-06-30 01:30 UTC, maxim-papier commented on TrackerAppScreenshotTest/TrackerAppScreenshotTest.swift
> +            rootViewController: TrackersVC(dependencies: dependencyContainer, analytic: YandexMetricaService())
Спасибо. Упустил, что добавился `pinService`. Исправлено.

2023-06-30 01:30 UTC, maxim-papier commented on TrackerAppScreenshotTest/TrackerAppScreenshotTest.swift
> +            rootViewController: TrackersVC(dependencies: dependencyContainer, analytic: YandexMetricaService())
Исправлено. Спасибо.

2023-06-30 01:31 UTC, maxim-papier commented on TrackerApp/CoreData/CategoryStore.swift
> +    //    func getCategory(at indexPath: IndexPath) -> Category? {
Исправлено. Прошу прощения.

2023-06-30 01:33 UTC, maxim-papier commented on TrackerApp/Scenes/EditTracker/EditTrackerViewModel.swift
> +        print("Checking validity")
Исправил. Спасибо за замечание.

2023-06-30 01:40 UTC, maxim-papier commented on TrackerApp/CoreData/RecordStore.swift
> +            if Calendar.current.isDate(record.date, inSameDayAs: currentDate!) {
Действительно, упустил. Спасибо. Исправил.

2023-06-30 01:47 UTC, maxim-papier commented on TrackerApp/CoreData/CategoryStore.swift
> +        for category in categories {
Спасибо. Так, действительно, лучше!

2023-06-30 01:50 UTC, maxim-papier commented
Спасибо вам за ревью. Замечания устранил. Была проблема с тестами, пришлось удалить тестовый таргет и package `SnapshotTesting`, а потом установить заново. Всё теперь работает. 

Хорошего дня!

2023-06-30 15:18 UTC, protos17 approved these changes

2023-06-30 15:18 UTC, protos17 commented on Podfile
> +  end
У меня не ставились поды - проблема в этом, что у тебя нет такого таргета - 'TrackerAppScreenshotTest'
поэтому рекомендую удалить с 10 по 13 строчки включительно

2023-06-30 15:18 UTC, protos17 commented on TrackerApp/Scenes/Statastic /StatisticVC.swift
> +    let viewModel: StatisticsViewModel
Эти константы рекомендую указать как private

2023-06-30 15:18 UTC, protos17 commented on TrackerApp/Scenes/EditTracker/EditTrackerViewModel.swift
> +    @Published var trackerTitle: String = "" { didSet { checkValidity() } }
Молодец, что использовал Combine!

2023-07-04 05:41 UTC, maxim-papier commented on Podfile
> +  end
Изменил таргет на правильный. Спасибо.

2023-07-04 05:42 UTC, maxim-papier commented on TrackerApp/Scenes/Statastic /StatisticVC.swift
> +    let viewModel: StatisticsViewModel
Сделано.

2023-07-04 05:43 UTC, maxim-papier commented
@protos17 спасибо за ревью. Извиняюсь, что долго отвечал. Этот спринт был моей последней задолженностью и курс я уже закончил. Немного приходил в себя. Ещё раз спасибо за помощь!

2023-07-04 05:49 UTC, merged